export const enum apiPath {
  HOME = '/home',
  PAST = '/trips/past',
  JOIN_TRIP = '/trips/join',
  COUNTRIES = '/countries',
  SPLIT = '/trips/{tripId}/settlements',
  USERS = '/users/code/{userCode}',
  BUDGET = '/trips/{tripId}/budget',
  EXPENSE = '/trips/{tripId}/expenses',
  TRIPCODE = '/trips/{tripId}/tripcode',
  TRIPS = '/trips/{tripId}',
  CREATE_TRIP = '/trips/create',
  SETTLEMENT = '/trips/{tripId}/settlements/{settlementId}',
  SETTLEMENT_MEMBER = '/trips/{tripId}/settlements/{settlementId}/expenses?memberId={memberId}',
  MY_PAGE = '/home/myPage',
  LOGOUT = '/auth/kakao/logout',
  EXCHANGE = '/api/exchangeRate',
  TRIP_COUNTRY = '/trips/{tripId}/countries',
  TRIP_DATE = '/trips/{tripId}/schedule',
  TRIP_INFO = '/trips/{tripId}/info',
  MY_FACE = '/home/myPage/face',
  SNAP_FACE = '/api/snap/face'
}
