export const enum apiPath {
  home = '/home',
  past = '/trips/past',
  joinTrip = '/trips/join',
  countries = '/countries',
  split = '/trips/{tripId}/settlements',
  users = '/users/code/{userCode}',
  budget = '/trips/{tripId}/budget',
  expense = '/trips/{tripId}/expenses',
  tripCode = '/trips/{tripId}/tripcode',
  trips = '/trips/{tripId}',
  createTrip = '/trips/create',
  settlement = '/trips/{tripId}/settlements/{settlementId}',
  settlementMember = '/trips/{tripId}/settlements/{settlementId}/expenses?memberId={memberId}',
  myPage = '/home/myPage',
  logOut = '/auth/kakao/logout',
  exchange = '/api/exchangeRate',
  tripCountry = '/trips/{tripId}/countries',
  tripDate = '/trips/{tripId}/schedule',
}
